= Dockerfile

Build and run the website.

== Overview

This Dockerfile is designed to streamline the build process of the
link:https://source2adoc.sommerfeld.io[source2adoc.sommerfeld.io] website. The purpose of this
Dockerfile is to generate the documentation sites using link:https://www.antora.org[Antora].

To avoid running the image as `root`, the permissions of `/usr/local/apache2/logs` are
changed to allow `www-data` to write logs. Additionally the default http port is changed to
`7880`, so keep that in mind when mapping ports in a `+docker run ...+` command. This way the
image can be used without root permissions because the httpd server inside the container is
started with the already existing user `www-data`.

The webserver exposes his status information through http://localhost:7880/server-status.

=== Prerequisites

This image has been developed and tested with Docker version 24.0.7 on top of Ubuntu 23.10.

== How to use

Use `docker run --rm -p "7880:7880" sommerfeldio/source2adoc-website:rc` to run the most
recent release candidate from DockerHub.
